server {
    listen 8080;
    server_name playlistrecycle.com www.playlistrecycle.com;
    root /usr/share/nginx/html;
    index index.html;
    
    location / {
        error_page 404 http://www.playlistrecycle.com;
        try_files $uri $uri/ $uri.html =404;
    }
}